### ISSUE TITLE
Can I use this on ConEmu / Cmder

### ISSUE THREAD

**Issue by lundeen-bryan** [cocopon/iceberg.vim#102]
OS: Windows 10 LTSB
Vim 8.2
Terminal ConEmu 210912 which is actually Cmder in Windows. Not sure why it says ConEmu in the help menu. 

I'm using Cmder which is also known as ConEmu but anyway, I'd like to use the iceberg colors in cmder. 
Not exactly sure how to do that but if anyone has, please post how.

**Comment by cocopon** [comment]
You can port it to other environments yourself. Please refer the color palette below:
https://gist.github.com/cocopon/1d481941907d12db7a0df2f8806cfd41
