### ISSUE TITLE
Light theme for Terminal.app

### ISSUE THREAD

**Issue by C0Nd3Mnd** [cocopon/iceberg.vim#103]
Environment:
- macOS 12.5
- Terminal.app

Would it be possible to add a profile file for Terminal.app for the light variation of this color scheme? Unless I'm missing something, the downloadable profile only includes the dark variation.

**Comment by cocopon** [comment]
There is no official release for the light theme, but you can generate it yourself using [terminal.sexy](terminal.sexy) and [.Xresources](https://gist.github.com/cocopon/1d481941907d12db7a0df2f8806cfd41?permalink_comment_id=3366408#gistcomment-3366408).

See this section for more information:
https://github.com/cocopon/iceberg.vim/tree/5ac9da61e8626d1218498a35e515f36387efe454#terminal-emulators
