### ISSUE TITLE
Support transparent

### ISSUE THREAD

**Issue by haunt98** [cocopon/iceberg.vim#106]
Environment:
- OS macOS 12.6
- NeoVim (`v0.7.2`)
- Terminal kitty (`0.26.2`)

If you have a trouble with coloration and are using Vim/Neovim with terminal:
- [x] Does your Vim support full colors? (`:set termguicolors`)
- [x] Does your terminal support full colors? (e.g. Terminal.app doesn't support it)

Hi there, Is there any config to set iceberg background transparent with kitty transparent yet?

**Comment by woodyZootopia** [comment]
I am using kitty+nvim and enjoying a transparent background. I believe kitty will use transparent background if you have the same background color in kitty and nvim. Check if you are using kitty iceberg colorscheme provided in README.md.

**Comment by gkeep** [comment]
> I believe kitty will use transparent background if you have the same background color in kitty and nvim.

That is correct. I built kitty colorschemes with that in mind.

Make sure you're using the correct colorscheme (see [here](https://github.com/cocopon/iceberg.vim#terminal-emulators)) and that you have transparency enabled in `kitty.conf`- for example, `background_opacity 0.8`. MacOS doesn't disable the compositor, so it's very unlikely to be a problem.

**Comment by cocopon** [comment]
Thank you for your help @woodyZootopia and @gkeep !
