### ISSUE TITLE
Visual selection is almost invisible

### ISSUE THREAD

**Issue by airblade** [cocopon/iceberg.vim#11]
In the screenshot the first `offset` is visually selected.  However it's almost impossible to see.

![screen shot 2017-06-15 at 1 05 03 pm](https://user-images.githubusercontent.com/7265/27180423-568a1022-51cb-11e7-81a6-7e5f137a6689.png)

Please could you make it clearer?

**Comment by cocopon** [comment]
Would you tell me your environment (OS, Vim version, terminal, etc.)?
Here is selection in my environment and it seems to be clearer:

<img width="370" alt="2017-06-15 23 05 30" src="https://user-images.githubusercontent.com/602961/27185151-6e0a4b96-521f-11e7-9c8f-73522d64b5a8.png">

- OS: macOS 10.12.4
- Vim: MacVim 8.0.596 (KaoriYa 20170512)

**Comment by airblade** [comment]
- OS X 10.11.6
- MacVim 8.0.586  via Homebrew

**Comment by cocopon** [comment]
Sorry for the late reply :bow:
Hmm, I checked it in my several environments and displays but I can see the selection clearly. It seems to be caused by your environment... You can make it clearer by editing the line of `iceberg.vim/colors/iceberg.vim`:

```vim
hi! Visual ctermbg=236 guibg=#363d5c
```

**Comment by airblade** [comment]
Ah, thank you.  I checked my vimrc and realised I had `hi! link Visual CursorLine` which I added for solarized-dark.  Commenting that out made all the difference.

Thanks!

**Comment by cocopon** [comment]
Oh, I didn't notice the cause. Thank you for your report!

**Comment by huyvohcmc** [comment]
`hi! Visual ctermbg=236 guibg=#363d5c`

Can we make this default? On my macOS 10.15.6 (alacritty terminal) I can barely see the visual as well and I don't override anything in the color scheme.

**Comment by cocopon** [comment]
You can add the line to your .vimrc like this:

```vim
colorscheme iceberg

" Mofify color definitions after setting color scheme
hi Visual ctermbg=236 guibg=#363d5c
```

**Comment by escherba** [comment]
I realize this issue is closed, but IMO the above should be the default -- the current selection background is almost imperceptible.
