### ISSUE TITLE
How could we create a dircolor theme?

### ISSUE THREAD

**Issue by AuxiliumEngineer** [cocopon/iceberg.vim#112]
Environment:
- OS: MacOS
- Vim (`NeoVim 0.9.0`)
- Terminal: Terminal.app

This isn't an issue with the vim theme, but i couldn't find a better place to put this.
The README mentions other implementations of iceberg and i hope this issue is appropriate.
BTW: Supporting Terminal.app rocks! So thank you for that.

It would be really nice to have one theme that is applied to every color in your terminal.
That is why i loved solarized, it is everywhere.
Iceberg could be the next solarized. Only missing part for me is a `dircolors` definition.
I can't estimate how difficult that would be (i happily copied a solarized `dircolors` a long time ago and never touched it again)

Feel free to ignore my request or share a different solution.

**Comment by cocopon** [comment]
Thank you for using Iceberg. What is `dircolors`? Can you share related information? e.g.  environments, official documents, screenshots, example codes, etc...
