### ISSUE TITLE
Colors Changed After Updating Neovim to Version 10

### ISSUE THREAD

**Issue by dk0bzar** [cocopon/iceberg.vim#117]
Environment:
- OS: Arch Linux
- Vim (`:version`): NVIM v0.10.0
- Terminal: xfce4-terminal

If you have a trouble with coloration and are using Vim/Neovim with terminal:
- [x] Does your Vim support full colors? (`:set termguicolors`)
- [x] Does your terminal support full colors? (e.g. Terminal.app doesn't support it)

![image](https://github.com/cocopon/iceberg.vim/assets/77533678/4234e1cc-9e19-4f64-968b-3f0022b68554)
After updating Neovim to version 10, I noticed that my color scheme has changed. The attached photo illustrates the differences:

-  Left: Arch Linux with Neovim v0.10.0
-  Right: Ubuntu with Neovim v0.7.2

For some reason, the color of the autocomplete menu has changed, and a white line has been added to the Nerdtree plugin.
**What Causes the Problem:**
I believe this issue arises because Neovim updated its default colors. To revert to the old colors, I need to set colorscheme vim.
**How can it be fixed:**
Set colorscheme vim before setting iceberg; possibly iceberg must be updated to do that after their `hi clear`. Otherwise my only option is to stick to Nvim 0.9.5. (The problem is that Iceberg doesn't set a full colorscheme but implicitly relies on some default links, which it shouldn't because it's not robust.)

**Comment by cocopon** [comment]
Hi, providing a summary would help the maintainers and make it easier for them to assist you.

- What is the problem?
- What is the cause?
- How can it be fixed?

**Comment by dk0bzar** [comment]
> Hi, providing a summary would help the maintainers and make it easier for them to assist you.
> 
> 
> 
> - What is the problem?
> 
> - What is the cause?
> 
> - How can it be fixed?

Updated my issue.

**Comment by dk0bzar** [comment]
> Hi, providing a summary would help the maintainers and make it easier for them to assist you.
> 
>     * What is the problem?
> 
>     * What is the cause?
> 
>     * How can it be fixed?

Updated issue.

**Comment by cocopon** [comment]
Thank you for updating the details.

It seems to be working fine in my environment... is there maybe another reason for this problem? (e.g. the config file, plugins, ...)

- macOS 13.6.7
- iTerm2 3.5.2
- NVIM v0.10.0
  ```
  :version
  NVIM v0.10.0
  Build type: Release
  LuaJIT 2.1.1716656478
  ```

<img width="682" alt="image" src="https://github.com/cocopon/iceberg.vim/assets/602961/0b6bfe83-707f-455f-a001-93e63c309806">

**Comment by dk0bzar** [comment]
Strange...
Are you using coc autocompletion?
[Here](https://gist.github.com/dk0bzar/9152f5df8840abd9edb7e64a2458a640) is my config file.
