### ISSUE TITLE
All 16 ANSI colors?

### ISSUE THREAD

**Issue by redtrumpet** [cocopon/iceberg.vim#12]
Hey,

I would like to port the iceberg color-scheme to [gnome-terminal](https://help.gnome.org/users/gnome-terminal/stable/). To do this I need to provide [16 colors](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors), but there are only 10 colors (plus a background color) in the palette:
![Palette](https://cocopon.github.io/iceberg.vim/assets/github/palette.png)

What are the other colors, or which other colors are provided in the [color-scheme](https://github.com/cocopon/iceberg.vim/blob/gh-pages/files/Iceberg.terminal) for Terminal.app?

**Comment by gagbo** [comment]
I downloaded the colorscheme for Terminal.app and used the (terminal.sexy)[terminal.sexy] web-site (thanks to [romainl/Apprentice](https://github.com/romainl/Apprentice#working-with-816-colors) ) to convert the scheme. In my case I used Konsole but it should be fine on gnome-terminal too. Below is the result of the conversion to .Xresources, that you can copy paste in the import field

```
! special
*.foreground:   #c6c8d1
*.background:   #121319
*.cursorColor:  #c6c8d1

! black
*.color0:       #161722
*.color8:       #373757

! red
*.color1:       #e27878
*.color9:       #f29b9e

! green
*.color2:       #b4be82
*.color10:      #ccdba0

! yellow
*.color3:       #e2a478
*.color11:      #edbe9d

! blue
*.color4:       #84a0c6
*.color12:      #a3bee3

! magenta
*.color5:       #a093c7
*.color13:      #c8b5e6

! cyan
*.color6:       #89b8c2
*.color14:      #b6d8de

! white
*.color7:       #d0d2db
*.color15:      #e9ebf5
```

**Comment by cocopon** [comment]
I'm considering about official 16 colors for this issue and #13. Please wait for a while.
