### ISSUE TITLE
Italic support

### ISSUE THREAD

**Issue by babygau** [cocopon/iceberg.vim#16]
Thank you for great colorscheme, could you please support italic text for this?

**Comment by cocopon** [comment]
Thank you for using Iceberg!

What does it mean 'italic text support'? Could you explain more about it or share some examples?

**Comment by babygau** [comment]
Tks you for quick response. Pls see the screenshot below, you could see *italic* comment with `stormpetrel` colorscheme:
<img width="2672" alt="screenshot 2017-11-10 23 09 03" src="https://user-images.githubusercontent.com/1514823/32658142-c31d431a-c66c-11e7-9824-0f81e26ab89f.png">
Moreover, [solarized8](https://github.com/lifepillar/vim-solarized8) and [gruvbox](https://github.com/morhetz/gruvbox) also have italic suport

**Comment by cocopon** [comment]
Thank you for the detailed information. If you want to make comments italic, you can do it by adding the following command after setting color scheme:

```vim
" colorscheme iceberg
hi Comment gui=italic cterm=italic term=italic
```

Or, modify `Comment` highlighting in iceberg.vim directly:

```vim
hi! Comment ctermfg=242 guifg=#6b7089 gui=italic cterm=italic term=italic
```

Is the problem solved?

**Comment by babygau** [comment]
Tks @cocopon, prob solved, but imo it should be better if you make it an option for your colorscheme.

**Comment by cocopon** [comment]
Thanks for your opinion!
I think many options will confuse many users. So I'm cautious for adding options.

**Comment by roket1428** [comment]
> Tks you for quick response. Pls see the screenshot below, you could see _italic_ comment with `stormpetrel` colorscheme:
> <img alt="screenshot 2017-11-10 23 09 03" width="2000" src="https://user-images.githubusercontent.com/1514823/32658142-c31d431a-c66c-11e7-9824-0f81e26ab89f.png">
> Moreover, [solarized8](https://github.com/lifepillar/vim-solarized8) and [gruvbox](https://github.com/morhetz/gruvbox) also have italic suport

Could you tell me which colorsheme do you have on that image? A link would be better.

**Comment by cocopon** [comment]
@roket1428 It may be [`stormpetrel`](http://colorswat.ch/vim/schemes/stormpetrel) contained in [seabird](https://github.com/nightsense/seabird).
