### ISSUE TITLE
Unexpected colours 

### ISSUE THREAD

**Issue by danielmorandini** [cocopon/iceberg.vim#19]
Environment:
Terminal.app version 2.8 on macOS highsierra 10.13
Terminal profile: iceberg
  
Issue:
The background colour and other UI components are in a weird grey (see image below)
<img width="916" alt="screen shot 2018-01-07 at 21 59 27" src="https://user-images.githubusercontent.com/10097445/34654043-13622a78-f3f6-11e7-971a-12f206a8e3c3.png">
  
Expected behaviour:
iceberg's colours (lovely btw, thank you @cocopon)

**Comment by cocopon** [comment]
Thank you for using Iceberg! It's not a bug and is caused by Terminal.app:
- Terminal.app doesn't support full colors
- So Vim uses 256-colors Iceberg

Please try below to solve the problem:
- Use a terminal that supports full color (e.g. iTerm)
- and enable `termguicolors` option of Vim

**Comment by danielmorandini** [comment]
Worked! 
I'm a little bit disappointed that I have to use another terminal app to use this colorscheme though..
Thank you anyway @cocopon !
