### ISSUE TITLE
vim-sneak support

### ISSUE THREAD

**Issue by kutsan** [cocopon/iceberg.vim#20]
It would be awesome if you can provide support for that plugin.

https://github.com/justinmk/vim-sneak/blob/1b02940ee4513575b2c3e44306ca945be685a7ce/doc/sneak.txt#L352-L367

**Comment by cocopon** [comment]
Thank you for the recommendation! Added Sneak support.

Normal:
![2018-02-09 20 29 22](https://user-images.githubusercontent.com/602961/36026066-d3e5a8b4-0dd8-11e8-9b15-3ec5ac8c92a7.png)

Vertical scope:
![2018-02-09 20 30 43](https://user-images.githubusercontent.com/602961/36026070-d6b792aa-0dd8-11e8-984b-1c7c797cfbe6.png)

**Comment by kutsan** [comment]
Looks awesome!
