### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by pkazmier** [cocopon/iceberg.vim#28]
Thank you for a fantastic theme! It looks beautiful and is easy on the eyes over long periods of time. I also enjoyed the slide deck you created on the design of the theme. It's very clear you are passionate about the aesthetic qualities, which I really appreciate. A lot of themes out there are littered with junk with little to no regard to an overall theme.

Before discovering your theme, I've been using gruvbox, which I think is another well-designed theme. It does use far too much red, which as you indicate should really be used sparingly for errors. This is the reason I was searching for a new theme, and how I randomly stumbled upon yours in a reddit thread somewhere.

Of course, now that I've found it, I want to make some small tweaks that I would contribute back. The problem is that I don't even know where to start as you've built your own theme generator. I see that I need to load `svss`, `pgmnt`, and `iceberg`, but I just don't know where to start. What command kicks off the whole process? Is there any chance you could put up a CONTRIBUTING document, so others can help contribute to your amazing theme?

Why am I interested in contributing? I like to use [vim-startify](https://github.com/mhinz/vim-startify). The gruvbox theme has improved the syntax highlighting to ensure the right aspects of the buffer are highlighted. For example, here is gruvbox version:

<img width="748" alt="screen shot 2018-06-10 at 10 32 50 am" src="https://user-images.githubusercontent.com/747855/41203228-bc00490a-6c99-11e8-8d48-a46629c912a1.png">

I want to make similar improvements for iceberg, which is currently rendered as this:

<img width="748" alt="screen shot 2018-06-10 at 10 33 05 am" src="https://user-images.githubusercontent.com/747855/41203244-dd8ef9c2-6c99-11e8-9ce4-df014f91d95a.png">

Gruvbox correctly deprioritizes the base path, which focuses attention to the filename itself. I find this improves readability significantly when using this plugin, so I'd like to create a PR for iceberg, but I need a little a guidance as to where to begin.

**Comment by cocopon** [comment]
Thank you for using Iceberg!

I added `build your own` section to README: https://github.com/cocopon/iceberg.vim/commit/aa4a9cd9b75486e941ce623f9beb3c73e5bcbf6a
Please refer the section for setting up a developing environment.

Or, PR with editing `colors/iceberg.vim` directly is also welcome! I'll apply your changes to source files like these( https://github.com/cocopon/iceberg.vim/commit/0444f991361eaae1fa54969b48dfe0423f381703, https://github.com/cocopon/iceberg.vim/commit/b21b68342be9e95d90dac7c5a3a4a00fbd374505 ).

**Comment by pkazmier** [comment]
Thanks for writers not those up. I hope to play around with the theme this weekend.

**Comment by pkazmier** [comment]
I submitted #31 to clarify a point in the build instructions. In addition, I submitted #30 to improve the look and feel of startify.
