### ISSUE TITLE
Thoughts on syntax consistency across languages

### ISSUE THREAD

**Issue by pkazmier** [cocopon/iceberg.vim#29]
I'm curious to your thoughts about consistency across languages in terms of common syntactic elements. For example, function definitions vim are not highlighted, but they are orange in ruby and go. Yet, internal vim function names are highlighted orange, but in go they are blue. This inconsistency would be easy to fix, but I'm curious if you are opposed to receiving PRs to improve this consistency or whether you don't agree in principle. Thanks!

**Comment by pkazmier** [comment]
I submitted #32 to fix.

**Comment by pkazmier** [comment]
As I've been trying to normalize the syntax highlighting across several languages, I'm torn on whether or not function invocations should be highlighted. What do you think? To give a concrete example, here is a screenshot of Go code normalized using your guidelines (as I have interpreted them):

<img width="1257" alt="screen shot 2018-07-01 at 12 39 02 pm" src="https://user-images.githubusercontent.com/747855/42137110-55da2a58-7d2c-11e8-9d07-7466050ce5ad.png">

And here is an alternate version where I experimented with highlighting function invocations and changing variable definitions to green to make them easy to spot:

<img width="1257" alt="screen shot 2018-07-01 at 12 39 39 pm" src="https://user-images.githubusercontent.com/747855/42137120-780757d6-7d2c-11e8-9ec0-fd4943fd30b6.png">

I would be very appreciative of your opinion on the matter.

**Comment by cocopon** [comment]
As a first step, I re-organized whole highlighting rules in b688907.
Because your changes and mine affect too wide range, I can't merge them...really sorry :cry:

**Comment by cocopon** [comment]
After much thought, I carefully resolved conflicts and merged your changes (#32) to the latest files. In the process, I modified some definitions in terms of consistency:

- `jsDestructuringBlock` should be highlighted as `Normal` (same as other variables)
- `jsFuncArgs`, `jsVariableDef` should be highlighted as `Normal` (same as other languages)
- `jsTemplateExpression` should be highlighted as `Normal` (because it should be highlighted as same as normal expressions)

  ```js
  // Example: `foo` should be highlighted as `Normal`
  `${foo['bar']}`
  ```

Feel free to reopen the issue if there are any problems.

**Comment by cocopon** [comment]
Ah I forgot to reply your suggestion, sorry...

> From a legibility point of view, it makes it much easier to read code. The only problem is if I use cyan for this function invocation, then there is too much cyan, which require tweaking maybe the color of variable definitions to green perhaps as shown in the alternate version above.

As I said in [this comment](https://github.com/cocopon/iceberg.vim/pull/32#issuecomment-406998054), at the moment, I think that current highlightings have enough readability so using less colors is better. But I am hesitating about which one is **really** good.

**Comment by cocopon** [comment]
Feel free to reopen the issue or create new one if you find new inconsistencies.
