### ISSUE TITLE
Now also as Xresources!

### ISSUE THREAD

**Issue by 97-109-107** [cocopon/iceberg.vim#3]
I know this is a strictly vim-related repo so I didn't do a pull request. I like this theme so much that I converted it to a Xresources file here: https://gist.github.com/97-109-107/063193d150df272a049b

If you feel like it, you could include it in the readme

**Comment by cocopon** [comment]
Great work! I'm very happy to hear that :smile:
Do you have any screenshot of it? I'd like to see it before including the readme.

**Comment by 97-109-107** [comment]
Sure thing!
Here it is:
![2015-08-30--1440950905_506x80_scrot](https://cloud.githubusercontent.com/assets/1902438/9568160/28eb6ab8-4f42-11e5-9b6e-38ab6f5fb1de.png)

**Comment by cocopon** [comment]
Thanks! Looks nice :)
