### ISSUE TITLE
Thoughts on a bold vim mode in the xlines?

### ISSUE THREAD

**Issue by pkazmier** [cocopon/iceberg.vim#33]
In my local version of iceberg, I use a bolded mode name in my xline configurations. It seems to be very common in most of the xline themes I've seen. Would you be opposed if I submitted a PR for this? Here is what it would look like with the 4 different vim modes:

<img width="1151" alt="screen shot 2018-06-24 at 3 42 24 pm" src="https://user-images.githubusercontent.com/747855/41823442-939e4bd8-77c5-11e8-8bf9-81c28d6f72d0.png">

**Comment by cocopon** [comment]
It seems to be enough even without bold style. I think users can find it easily with its position (on the far left) and colored background. What do you think?

Additionaly, there are more non-bold themes than others in [default themes of lightline.vim](https://github.com/itchyny/lightline.vim/tree/master/autoload/lightline/colorscheme). Here is the straightforward survey of them:

**Bold (7 themes):**
- deus.vim
- landscape.vim
- materia.vim
- material.vim
- one.vim
- powerline.vim (default)
- srcery_drk.vim

**Non-bold (17 themes):**
- 16color.vim
- OldHope.vim
- PaperColor.vim
- PaperColor_dark.vim
- PaperColor_light.vim
- Tomorrow.vim
- Tomorrow_Night.vim
- Tomorrow_Night_Blue.vim
- Tomorrow_Night_Bright.vim
- Tomorrow_Night_Eighties.vim
- darcula.vim
- jellybeans.vim
- molokai.vim
- nord.vim
- seoul256.vim
- solarized.vim
- wombat.vim

**Comment by pkazmier** [comment]
Fair enough. I need to maintain my own branch for lightline as I need more “punch” as insert mode is not different enough from normal mode for my taste. I’m thinking of doing something similar to the insert mode of the powerline theme, but with the iceberg hues. 

<img width="920" alt="image" src="https://user-images.githubusercontent.com/747855/42398363-34993bfc-812f-11e8-8cec-9b0de71e6c4f.png">
