### ISSUE TITLE
Thoughts on italic comments?

### ISSUE THREAD

**Issue by pkazmier** [cocopon/iceberg.vim#34]
What would your suggestion be on how to add **optional** italic comments? Because the theme files are generated using **pgmt**, I'm not sure how best to add an `if` statement to check a flag. I suppose simplest approach is just to add the something like the following after they load iceberg if they want italic comments:
```vim
highlight Comment cterm=italic gui=italic
```
I was curious as to your thoughts.

**Comment by cocopon** [comment]
I think options will confuse many users. So I'm cautious for adding options.
(please refer #16 for previous discussion)

**Comment by pkazmier** [comment]
Fair enough, it’s trivial to add in one’s vimrc.
