### ISSUE TITLE
New theme for the bumblebee statusbar

### ISSUE THREAD

**Issue by whzup** [cocopon/iceberg.vim#39]
Hello @cocopon, thanks for sharing your amazing color scheme. It pleased me so much that I made a theme for the [bumblebee status bar](https://github.com/tobi-wan-kenobi/bumblebee-status). You can include it in the README if you want to 😄

**Comment by cocopon** [comment]
Thank you! Could you share the repository/code and some screenshots? I'd like to see its coloration before merging your work.

**Comment by whzup** [comment]
Sure! For a screenshot see [here](https://github.com/tobi-wan-kenobi/bumblebee-status/tree/master/screenshots/themes) and the code is [here](https://github.com/tobi-wan-kenobi/bumblebee-status/blob/master/themes/iceberg-powerline.json). I have not opened a repo for it since I already provided it to the maker of the bumblebee-statusbar but if you have anything you'd like to have changed I'm sure he has nothing against some correctional PRs :smile:

**Comment by whzup** [comment]
@cocopon I've been trying to get behind your coloring concept yesterday and I made another theme that may be closer to the "feel" of the iceberg theme:

![bumblebee-iceberg](https://user-images.githubusercontent.com/39431903/45407257-285ffa00-b669-11e8-9880-a8eee6bdabb4.png)

Orange background means warning, red background means critical, green script means "good" and light blue script means "charging".
I also thought about changing the colours in the theme above to the ones that you use in the airline theme and only let the script vary in colour. What do you think?

But when "analysing" your coloring concept I got curious. I read through your presentation slides for "Creating Your Lovely Color Scheme" and you say there that you fixed saturation and brightness and played with the hues. But for the script colours you also changed the saturation and brightness slightly is there a reason for that?

**Comment by cocopon** [comment]
Latter one looks nice! It express the concept well.

> But for the script colours you also changed the saturation and brightness slightly is there a reason for that?

The basic concept is as described above. It works well, but more specifically, we should consider about a property of our eyes. We feel green is brighter than other colors even though they have the same brightness. Based on this, I fine-tuned their saturation and brightness.

You can google "luminous efficiency function" for more detailed information:
https://en.wikipedia.org/wiki/Luminosity_function

**Comment by whzup** [comment]
I wasn't aware of this fact! Thanks for sharing it. That's very interesting, did you use a tool to find out which correction you had to do?

I redesigned the "airliney" status bar:
![bumblebee-iceberg-powerline-new](https://user-images.githubusercontent.com/39431903/45423864-f19fd900-b694-11e8-8a67-0db232b6b445.png)

The color cycle resembles your design of the airline bar in the vim editor and goes back and forth between them. Again a warning is orange and the blue part is charging. I think it looks better now. What's your opinion?

**Comment by whzup** [comment]
Ok, thank you! I'll go ahead and submit those :smile:

**Comment by whzup** [comment]
Hey @umop3plsdn! Uh, I hoped this wouldn't happen 😄. I really respect the work of @cocopon and I wouldn't want to use a name that indicates any relation to the iceberg theme if he does not appreciate it. So I'd go with "colorful" unless @cocopon hasn't got any issue if it's called "iceberg-colors" or something like that.

**Comment by cocopon** [comment]
@whzup Looks good! I think "iceberg-colors" or "iceberg-rainbow" is good for the coloration. Please choose whichever you like.
