### ISSUE TITLE
No check for termguicolors

### ISSUE THREAD

**Issue by LunarLambda** [cocopon/iceberg.vim#40]
- OS Windows 10
- Vim (`:version`) VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep 11 2018 22:03:24)
MS-Windows 64-bit console version
Included patches: 1-369
Compiled by appveyor@APPVYR-WIN
Huge version without GUI.
- Terminal Windows

Start of file checks for 256 colors
Windows console supports truecolor (and termguicolors is set) but t_Co reports 16 (can't be changed either). Thus a check for &t_Co < 256 at the start of the file fails, and the colorscheme doesn't load. Removing the check altogether works.

Should change `if !has('gui_running') && &t_Co < 256` to include a check for termguicolors.

**Comment by cocopon** [comment]
It seems to work well in my environment.

- Windows 10 Pro (latest build)
- Bash on Windows
- Vim 8.1

![2018-10-13](https://user-images.githubusercontent.com/602961/46904935-2b2f6280-cf27-11e8-81a3-505cb6022f97.png)

- Is the problem still occur in the latest environment?
- Is "Terminal Windows" meant to "Bash on Windows"? Or "Command Prompt"?
- Do other color schemes with full colors (e.g. gruvbox, etc.) work fine?

**Comment by LunarLambda** [comment]
First of I apologize for forgetting to respond, it kinda left my radar after I stopped using Windows, but I kinda ran into it again when on mate-terminal, which sets TERM to xterm by default, but supports truecolor regardless, didn't work with the colorscheme.

As for the original issue, I said `MS-Windows 64-bit console version`, so specifically the 'Comamnd Prompt' version.

The actual issue is that it  *does* work, but only if TERM reports 256 colors, regardless of whether truecolor (termguicolors) is set/supported.

A fix would be changing the if statement at the start to

```
if ! has('gui_running') && ! &termguicolors && &t_Co < 256
    finish
endif
```

I hope this helps.

**Comment by LunarLambda** [comment]
I've opened a PR about it.

**Comment by cocopon** [comment]
Closed the issue because it has not had recent activity.
Feel free to reopen this if you still have the problem.
