### ISSUE TITLE
Visual Studio Code support

### ISSUE THREAD

**Issue by gggggtj** [cocopon/iceberg.vim#42]
Would you implement iceberg for Visual Studio Code?

**Comment by cocopon** [comment]
I've already implemented the one, but don't publish yet. Are you interested in it?

![2018-12-27 11 40 05](https://user-images.githubusercontent.com/602961/50462986-32b1c400-09cc-11e9-845c-9c5a1a8fe1fa.png)

**Comment by gggggtj** [comment]
Oh, that's the one i've been looking for!!
I hope you publish it if you don't mind.

**Comment by cocopon** [comment]
Released the very first version of the theme! Enjoy :)
https://github.com/cocopon/vscode-iceberg-theme

You can install the theme on Visual Studio Code:
- Show Command Palette
- Choose `Extension: Install Extensions`
- Search `iceberg`
- Install `Iceberg Theme` (extension identifier: `cocopon.iceberg-theme`)
