### ISSUE TITLE
Ruby syntax highlighting is partially broken

### ISSUE THREAD

**Issue by marko-avlijas** [cocopon/iceberg.vim#43]
Environment:
- OS - Linux Mint 18.3
- Vim (`:version) 
Vi IMproved 8.1 (2018 May 17, compiled May 24 2018 22:39:34)
Included patches: 1-22
Huge version with GTK2 GUI.`
- Terminal  Gnome terminal and tmux

If you have a trouble with coloration and are using Vim/Neovim with terminal:
- [x] Does your Vim support full colors? (`:set termguicolors`)
- [x] Does your terminal support full colors? (e.g. Terminal.app doesn't support it)

24 bit colors work fine, tested with a script.

Ruby syntax highlighting is partially broken for me. I am attaching screenshot. It's in tmux. On left is theme one which works perfectly and on right is iceberg which ignores lots of stuff.

![image](https://user-images.githubusercontent.com/8687315/50452911-4eba5480-093d-11e9-80ee-9e023e7a6f3e.png)

**Comment by cocopon** [comment]
Could you share the code in plain text or its URL? I'll check the detail in my environment.

**Comment by marko-avlijas** [comment]
It was this file: https://github.com/marko-avlijas/blogger_tutorial/blob/master/app/controllers/articles_controller.rb

**Comment by cocopon** [comment]
Here is the result in my environment. It seems to work well:
![2018-12-28 11 38 19](https://user-images.githubusercontent.com/602961/50500504-1f1e6000-0a95-11e9-923e-31d862fffee8.png)

- What is the filetype of the buffer? (`echo &ft`)
- Do you use any plugins for Ruby?

If you can share your .vimrc, it helps me to reproduce the issue.

**Comment by marko-avlijas** [comment]
File type is ruby. I am using no ruby plugins.
This is my [.vimrc](https://github.com/cocopon/iceberg.vim/files/2726828/vimrc.txt)

**Comment by cocopon** [comment]
I found the cause of the problem. It's caused by your default color scheme palenight.vim. It overwrites the default link structure:

https://github.com/drewtempelmeyer/palenight.vim/blob/139f5b929a8be2530c7386a5b4610d4459941199/colors/palenight.vim#L347

**Comment by cocopon** [comment]
Feel free to reopen the issue if you still have the problem.

**Comment by marko-avlijas** [comment]
Oh wow, thank you. I'll look into this later this week.
