### ISSUE TITLE
Add support for ALE's virtual text feature

### ISSUE THREAD

**Issue by kutsan** [cocopon/iceberg.vim#44]
See this https://github.com/w0rp/ale/blob/73ca1e71918a0b50b7bbcbed91857c3618ad93cc/doc/ale.txt#L1919-L1923.

I think linking the existing ones is suitable for the most needs.

```vim
highlight! link ALEVirtualTextError ALEErrorSign
highlight! link ALEVirtualTextWarning ALEWarningSign
highlight! link ALEVirtualTextStyleError ALEVirtualTextError
highlight! link ALEVirtualTextStyleWarning ALEVirtualTextWarning
highlight! link ALEVirtualTextInfo ALEVirtualTextWarning
```

**Comment by cocopon** [comment]
Added highlighting groups for the feature.

`~StyleError`, `~StyleWarning` and `~Info` seems to be linked by default:
https://github.com/w0rp/ale/blob/3b96ab43fb7adede47705bd3b6efcaddb315a68d/autoload/ale/virtualtext.vim#L15-L33

**Comment by kutsan** [comment]
Thanks, appericated it.
