### ISSUE TITLE
Add support for git-messenger.vim

### ISSUE THREAD

**Issue by ress997** [cocopon/iceberg.vim#45]
See this <https://github.com/rhysd/git-messenger.vim/blob/c2b7be0a8bed24d5132c57f0f35c92446da639e1/doc/git-messenger.txt#L247-L269>.

宜しくおねがいします

**Comment by cocopon** [comment]
Added support for the plugin!

![image](https://user-images.githubusercontent.com/602961/56399663-7cc7f980-628a-11e9-8804-8e9d02b1d42d.png)

![image](https://user-images.githubusercontent.com/602961/56399683-92d5ba00-628a-11e9-87cd-58a284fc671b.png)
