### ISSUE TITLE
Could you add plug.vim support?

### ISSUE THREAD

**Issue by roket1428** [cocopon/iceberg.vim#46]
Basicly plug.vim has an keyword to install plugins: "Plug".
Its highlight group is "vimIsCommand"

**Comment by cocopon** [comment]
`vimIsCommand` is also applied to many other symbols.

For example, here is the result of `:hi link vimIsCommand Error`. Red symbols are all `vimIsCommand`:

![スクリーンショット 2019-06-16 10 34 49](https://user-images.githubusercontent.com/602961/59557991-6340f500-9022-11e9-923c-3b697e973eb8.png)

If you want to change them, add `hi link vimIsCommand FOOBAR` to your .vimrc.

- Blue: `hi link vimIsCommand Statement`
- Green: `hi link vimIsCommand Special`
- Light blue: `hi link vimIsCommand Identifier`
- Orange: `hi link vimIsCommand Title`
- Purple: `hi link vimIsCommand Constant`

**Comment by roket1428** [comment]
Yeah, I know. I just wanted you to add suppor for plug.vim.
Maybe new users who don't know little bit of vimfu couldn't do that, you get the idea.

**Comment by cocopon** [comment]
I understand your kindness. But color schemes cannot highlight the specific keyword `Plug`. It is a responsibility of syntax plugins.

So if you want to highlight the keyword, create a new syntax plugin for .vim files. You can define a new highlighting group for the specific keyword in the file. It may help Vim beginners.

**Comment by roket1428** [comment]
I see. Thanks for help dude, very nice colorscheme, by the way.

I just wanna know something else, too: Do you have any user css flie for any kind of web site or something that based on iceberg? If you have, I'm glad to see that and tweak it for other sites, you know I'll be copycat. :)

**Comment by cocopon** [comment]
Here is the CSS file for the [official web site](https://cocopon.github.io/iceberg.vim/):
https://github.com/cocopon/iceberg.vim/blob/gh-pages/assets/css/style.css

You can also generate it with my plugin [colorswatch.vim](https://github.com/cocopon/colorswatch.vim) like this:

```vim
:ColorSwatchGenerate original css
```

I hope this helps.

**Comment by roket1428** [comment]
I totaly forgot your web site. :)
