### ISSUE TITLE
Different colors for markdown heading levels?

### ISSUE THREAD

**Issue by ManiacalAce** [cocopon/iceberg.vim#48]
I love this color scheme, but in markdown files, all the heading levels are of the same color - making it difficult to make out different sections. 

I know nothing of design and palettes, but would it be possible to have different colors for different heading levels?

**Comment by cocopon** [comment]
Thank you for using Iceberg! I don't think to add these definitions by default, but you can declare them manually in your .vimrc:

```vim
" h2 to green
hi! link markdownH2 Special

" h3 to purple
hi! link markdownH3 Constant

" ...
```

![スクリーンショット 2019-07-04 9 30 11](https://user-images.githubusercontent.com/602961/60632085-54d64400-9e3e-11e9-9c48-c04ca02a97d9.png)
