### ISSUE TITLE
vim-fugitive diff support

### ISSUE THREAD

**Issue by picaoao** [cocopon/iceberg.vim#49]
it would be great if we could add support for vim-fugitive diff !
the current diff colours don't really work well and are very high contract making it very hard to read the code.

**Comment by cocopon** [comment]
Could you share the screenshot or reproduction steps?

**Comment by picaoao** [comment]
iTerm2 3.2.9
tmux 2.8
NVIM v0.3.1
OSx 10.14.5



![image](https://user-images.githubusercontent.com/15788170/61364601-18fb9f80-a87e-11e9-819f-fe266e5d3d70.png)

**Comment by cocopon** [comment]
Is your Iceberg in the screenshot customized? Are you using 256-colors Iceberg or full colors (with `termguicolors` option)? It looks a bit different from what I expected.

Here are screenshots in my environment:

Full colors (with `termguicolors`):
![screenshot_full](https://user-images.githubusercontent.com/602961/61443847-3f583280-a985-11e9-8c10-6b42c4d4ecd6.png)

256 colors (without `termguicolors`):
![screenshot_256](https://user-images.githubusercontent.com/602961/61443806-2e0f2600-a985-11e9-9696-7021d2a6b893.png)

**Comment by picaoao** [comment]
Im using `set termguicolors` in nvim, but I'm using tmux with true colours, which I believe it uses 24bit colours.

```
# Default terminal is 256 colors
set -g default-terminal "screen-256color"

# Add truecolor support
set-option -ga terminal-overrides ",screen-256color:Tc"
```

If I don't use tmux, I get the same behaviour as you.

Nevertheless I think it would be nicer to do a bit like GitHub does, and don't let the background (green) hide the colour syntax of the code in the diffs.

**Comment by cocopon** [comment]
After some experiments, I think the current one is still better than other versions.

**The current syntax:**
<img width="955" alt="2019-09-12 17 29 51" src="https://user-images.githubusercontent.com/602961/64858190-a3cfff00-d661-11e9-93cf-15c1d02c9800.png">

**With filetype syntax:**
<img width="955" alt="2019-09-12 17 33 02" src="https://user-images.githubusercontent.com/602961/64858290-e7c30400-d661-11e9-9355-cbd221d69047.png">

**With filetype syntax (fine-tuned for text readability):**
<img width="955" alt="2019-09-12 17 29 16" src="https://user-images.githubusercontent.com/602961/64858215-ba765600-d661-11e9-9362-c748c3e1bdba.png">

The most important thing of the diff preview is what are added, removed, and changed. Filetype syntax seems to reduce readability of block-level diff information.

**Comment by picaoao** [comment]
I think the last screenshot (w/ filetype syntax and tuned) is the best.

I allows both understanding the diffs and at the same time time, read code better. That is definitely an advantage regarding the original approach (just understanding that there is a diff).

I understand that this could be a matter of personal taste.
So my suggestion is to make it configurable.

Would that be possible ?

**Comment by cocopon** [comment]
Currently I don't have a plan to add options. Even now there are four variants (gui dark, gui light, cui dark, cui light), so one option will make four variations. And if we add one more option, it increases from 8 to 16 (4 * 2 * 2).
