### ISSUE TITLE
airline/lightline support

### ISSUE THREAD

**Issue by vdrandom** [cocopon/iceberg.vim#5]
The title says it all. Iceberg is an amazing theme, it would be more complete if it supported [airline](https://github.com/vim-airline/vim-airline) and [lightline](https://github.com/itchyny/lightline.vim) plugins which are quite popular among vim users.

You don't even have to start from scratch: apparently, [neodark](https://github.com/KeitaNakamura/neodark.vim) theme already has themes for these plugins that uses colors set by the vim colorscheme. I know one could use it from neodark, but it would have been more convenient if the airline/lightline themes were included.

**Comment by cocopon** [comment]
Done! Thank you for the advice and helpful information!
