### ISSUE TITLE
Better support for vim-elixir

### ISSUE THREAD

**Issue by picaoao** [cocopon/iceberg.vim#50]
it would be great if we could have better support for https://github.com/elixir-editors/vim-elixir.

**Comment by cocopon** [comment]
Added support for vim-elixir!

![2019-07-19 9 24 41](https://user-images.githubusercontent.com/602961/61500676-46c02000-aa07-11e9-8cd9-b8ca58cfd5e0.png)

**Comment by picaoao** [comment]
Awesome 👏
