### ISSUE TITLE
Suckless/Simple Terminal (ST) color scheme support

### ISSUE THREAD

**Issue by roket1428** [cocopon/iceberg.vim#51]
I wanted to add Iceberg color scheme to [ST](https://st.suckless.org).

I hope you'll add this to the list (if you do, please, refer me as ***vejetaryenvampir***).
Yours sincerely.

Here it is:

```c
static const char *colorname[] = {
  /* 8 normal colors */
  "#161821", /* black   */
  "#e27878", /* red     */
  "#b4be82", /* green   */
  "#e2a478", /* yellow  */
  "#84a0c6", /* blue    */
  "#a093c7", /* magenta */
  "#89b8c2", /* cyan    */
  "#c6c8d1", /* white   */

  /* 8 bright colors */
  "#6b7089", /* black   */
  "#e98989", /* red     */
  "#c0ca8e", /* green   */
  "#e9b189", /* yellow  */
  "#91acd1", /* blue    */
  "#ada0d3", /* magenta */
  "#95c4ce", /* cyan    */
  "#d2d4de", /* white   */
};

unsigned int defaultfg = 7;
unsigned int defaultbg = 0;
static unsigned int defaultcs = 7;
static unsigned int defaultrcs = 0;
```

**Comment by cocopon** [comment]
Thank you for porting Iceberg!

- Could you share some screenshots of the theme?
- Can you host the theme file yourself? (e.g. [Gist](https://gist.github.com))
  I'm not a ST user so cannot maintain the theme. Hosting it yourself is better way to keep its quality. I'll add a URL to README.

**Comment by roket1428** [comment]
> Thank you for porting Iceberg!
> 
> * Could you share some screenshots of the theme?
> * Can you host the theme file yourself? (e.g. [Gist](https://gist.github.com))
>   I'm not a ST user so cannot maintain the theme. Hosting it yourself is better way to keep its quality. I'll add a URL to README.

Can I use my account on notabug.org? Because I don't like github (I use my friend's account for now).

**Comment by cocopon** [comment]
> Can I use my account on notabug.org? Because I don't like github (I use my friend's account for now).

I do not mind what service you use. Please share the link and some screenshots.

**Comment by roket1428** [comment]
> > Can I use my account on notabug.org? Because I don't like github (I use my friend's account for now).
> 
> I do not mind what service you use. Please share the link and some screenshots.

I'll do it when I fix Xorg...

**Comment by roket1428** [comment]
> > Can I use my account on notabug.org? Because I don't like github (I use my friend's account for now).
> 
> I do not mind what service you use. Please share the link and some screenshots.

I hope it is clear enough: https://notabug.org/vejetaryenvampir/st-iceberg

**Comment by cocopon** [comment]
Thank you! I checked screenshots and it looks good to me. Added a link in c94e82a.

BTW, I recommend adding a license file to your repository. It may help your theme users.

**Comment by roket1428** [comment]
> Thank you! I checked screenshots and it looks good to me. Added a link in [c94e82a](https://github.com/cocopon/iceberg.vim/commit/c94e82ab8c62c2b6f09c00752199692e4af1c836).
> 
> BTW, I recommend adding a license file to your repository. It may help your theme users.

I think I chose GPLv3 but not added. :)

**Comment by cocopon** [comment]
> I added manually now. Now, can I close this issue?

Sure! Thank you for contributing!

**Comment by roket1428** [comment]
> > I added manually now. Now, can I close this issue?
> 
> Sure! Thank you for contributing!

You're welcome!
