### ISSUE TITLE
Add support for vim-erlang-runtime

### ISSUE THREAD

**Issue by picaoao** [cocopon/iceberg.vim#53]
It would be super awesome if we could add also support for https://github.com/vim-erlang/vim-erlang-runtime !

🙏

**Comment by cocopon** [comment]
Is there a good example for the issue? I tried some codes and they seem to be fine to me.

![screenshot 2019-08-28 10 46 07](https://user-images.githubusercontent.com/602961/63819664-12823c80-c981-11e9-8163-ca3cd801062c.png)

**Comment by picaoao** [comment]
it could follow the same colour template as in elixir, and be more colour `rich`.

 Examples I could quickly find:
  - atoms and variables have the same colour 
  - functions declaration in elixir are yellowish, and here are white
  - module:function() calls, the module is white, where in elixir they are blue.
  - _Variables are grey in elixir, in Erlang they are green and there is no difference between _vars and normal vars.

These are just some things I could catch.
The ideal would be to use the same schema as in elixir, because they sort of use the same `grammar`.... and with that have a more consistent look across the languages.

**Comment by cocopon** [comment]
Could you share some example codes and screenshots for those? I don't know Erlang/Elixir well.
