### ISSUE TITLE
Iceberg for other environments

### ISSUE THREAD

**Issue by gkeep** [cocopon/iceberg.vim#55]
Hello! Thank you for your theme. I love it so much I took it to almost every app I use (or did use) often. So over some time I've got a collection of iceberg for other environments. 

1. for [kitty](https://github.com/kovidgoyal/kitty) terminal emulator - [gist](https://gist.github.com/gkeep/9b6f3e86d44542f73b526183095d5c3a)

2. [alternative theme](https://github.com/gkeep/iceberg-dark#lightlinevim) for lightline

3. [tmux](https://github.com/gkeep/iceberg-dark#tmux)

4. [bumblebee-status](https://github.com/gkeep/iceberg-dark#bumblebee-status) theme 

Last three are *heavily inspired* by your theme, because I prefer darker statuslines. I can make a version of tmux theme with lighter colors, if you want to. 

It would be nice if you could add links to my gist and [iceberg-dark](https://github.com/gkeep/iceberg-dark) repo.

**Comment by roket1428** [comment]
I also made a duckduckgo.com theme but it is a feature of duckduckgo itself. So, I cannot share it because of some trolls can change it. :/ I wish duckduckgo could have read only themes.

**Comment by cocopon** [comment]
Great! I added your work to readme. After seeing your lightline theme, I think I should update the original one... (it's hard to see)
