### ISSUE TITLE
ZSH color scheme support

### ISSUE THREAD

**Issue by ridhwaans** [cocopon/iceberg.vim#57]
Environment:
- OS Win10 - (with WSL Ubuntu), Mac Catalina
- Vim - (`:version`) latest
- Terminal - Hyper, iTerm2

If you have a trouble with coloration and are using Vim/Neovim with terminal:
- [ x] Does your Vim support full colors? (`:set termguicolors`)
- [ x] Does your terminal support full colors? (e.g. Terminal.app doesn't support it)

Are you taking any requests to port iceberg to ZSH, (or oh-my-zsh and antigen plugin managers)?
Interested in adding iceberg to zshrc

**Comment by cocopon** [comment]
I think it's not an issue of zsh but of a terminal. You can use [hyper-iceberg](https://github.com/cocopon/hyper-iceberg) for Hyper or generate iTerm color preset with [terminal.sexy](https://terminal.sexy/) and [.Xresources file](https://gist.github.com/cocopon/1d481941907d12db7a0df2f8806cfd41). Please refer the [section](https://github.com/cocopon/iceberg.vim#for-other-environments) of readme.
