### ISSUE TITLE
Eyecandy used in README

### ISSUE THREAD

**Issue by ApolloBian** [cocopon/iceberg.vim#59]
Hi, may I ask what is the program used in this pic?
![image](https://user-images.githubusercontent.com/13659369/75004982-dd762300-54a7-11ea-90b6-e002094682c3.png)
I wrote a python script to achieve a similar result but this one looks very neat!

**Comment by cocopon** [comment]
That is my small program written in Go!
https://gist.github.com/cocopon/177716dff3580e69df53431399fb86ef

**Comment by ApolloBian** [comment]
That's a very cool script!
