### ISSUE TITLE
The selected line is hard to read in denite.nvim.

### ISSUE THREAD

**Issue by bicycle1885** [cocopon/iceberg.vim#6]
Hi,

I use iceberg.vim in neovim/[denite.nvim](https://github.com/Shougo/denite.nvim) and found the selected line is very difficult to read in a selection pane as follows:
![screen shot 2016-12-29 at 19 48 51](https://cloud.githubusercontent.com/assets/905683/21542338/6620c6ce-ce00-11e6-9fcf-0c9a2b59fba8.png).

The top cursor line is in "blackout" and I cannot read the matching word at the line (matching words at other lines are highlighted properly). I guess this is partially due to this color scheme because [jellybeans](https://github.com/nanotech/jellybeans.vim) does not cause this problem.

Can you fix that or should I file the issue at denite.nvim?

**Comment by cocopon** [comment]
Thank you for reporting!

It seems to be conflicted between cursorline and highlight for search keywords. I think Jellybeans uses a lighter foreground color for search keywords, so this problem doesn't occur.

I'm trying to install denite.nvim to reproduce the issue and struggle against the chaos of Vim, pyenv, and Python3 support... wait for a while please.

**Comment by bicycle1885** [comment]
Thank you! No rush, please take your time.

**Comment by cocopon** [comment]
Changed style for matched text, how about it?

![2017-01-05 16 39 37](https://cloud.githubusercontent.com/assets/602961/21672535/7903d2b6-d366-11e6-8cda-744876dcecce.png)

**Comment by bicycle1885** [comment]
Looks much better! Thank you a lot 💯
