### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by cocopon** [cocopon/iceberg.vim#62]
TODO:
- [x] Deciding a concept
- [x] GUI colors
- [x] Basic cterm colors
- [x] ANSI 16 colors
- [x] Special colors for plugins
- [x] airline/lightline themes (#61  by [gkeep](https://github.com/gkeep))
- [x] Finishing

Current development version:
![image](https://user-images.githubusercontent.com/602961/76682432-96f78c80-663f-11ea-9e81-ffaa198a7849.png)

**Comment by cocopon** [comment]
Updates:

cterm:
![cterm](https://user-images.githubusercontent.com/602961/79625485-7651b380-8164-11ea-8105-560f0e6c6009.png)

ANSI 16 colors:
![ansi](https://user-images.githubusercontent.com/602961/79625589-efe9a180-8164-11ea-84c1-c35fd77beeb6.png)

**Comment by gkeep** [comment]
Can you share the colors for statusbar? I'll look into adopting them to #61.

**Comment by cocopon** [comment]
I haven't finished to adjust colors yet, please wait ;)

**Comment by cocopon** [comment]
Light theme is still in progress but I plan to publish it as public beta. Could you update the pull request with the current palette? I'll merge it. @gkeep

```vim
" lightline
let col_base     = ['#8b98b6', '#cad0de', 244, 251]
let col_edge     = ['#e8e9ec', '#757ca3', 252, 243]
let col_gradient = ['#e8e9ec', '#9fa6c0', 252, 247]
let col_nc       = ['#8b98b6', '#cad0de', 244, 251]
let col_tabfill  = ['#8b98b6', '#cad0de', 244, 251]
let col_normal   = ['#e8e9ec', '#757ca3', 252, 243]
let col_error    = ['#e8e9ec', '#cc517a', 254, 125]
let col_warning  = ['#e8e9ec', '#c57339', 254, 130]
let col_insert   = ['#e8e9ec', '#2d539e', 254, 25]
let col_replace  = ['#e8e9ec', '#c57339', 254, 130]
let col_visual   = ['#e8e9ec', '#668e3d', 254, 64]
let col_tabsel   = ['#e8e9ec', '#757ca3', 252, 243]
```

```vim
" airline
let col_base     = ['#8b98b6', '#cad0de', 244, 251]
let col_edge     = ['#e8e9ec', '#757ca3', 252, 243]
let col_error    = ['#e8e9ec', '#cc517a', 254, 125]
let col_gradient = ['#e8e9ec', '#9fa6c0', 252, 247]
let col_nc       = ['#8b98b6', '#cad0de', 244, 251]
let col_warning  = ['#e8e9ec', '#c57339', 254, 130]
let col_insert   = ['#e8e9ec', '#2d539e', 254, 25]
let col_replace  = ['#e8e9ec', '#c57339', 254, 130]
let col_visual   = ['#e8e9ec', '#668e3d', 254, 64]
let col_red      = ['#cc517a', '#e8e9ec', 125, 254]
```

**Comment by gkeep** [comment]
Great, I'll update it shortly.

By the way, do you mind if I make a [color table](https://github.com/dracula/dracula-theme#color-palette) like Dracula theme has?
Ideally, I'd put it in the wiki and it would be for both dark and light themes.

**Comment by gkeep** [comment]
### Feedback:
Light theme looks great! But, there are a few issues:
1. **Cursor color**: while cursor color looks good, when it is box-shaped, it is *very* hard to see, when it is beam-shaped.
![comparison](https://user-images.githubusercontent.com/20600053/82061354-43ea9600-96d1-11ea-9b96-0ff976ac2a7f.png)
2. Shouldn't dark theme be the default? Might be an issue on my end, but vim loads light theme when `background` is not set.
3. **Port to VSCode**: since dark theme is available on VSCode marketplace, I think it's fair to ask to port it to VSCode (I might be able to look into this myself, if you don't mind).

**Comment by cocopon** [comment]
Thank you for quick feedback!

> 1. Cursor color

Here is the color in my environment and its definition (left: background, right: foreground). It should be dark:
<img width="655" alt="cursor-light" src="https://user-images.githubusercontent.com/602961/82063047-f4728d00-9705-11ea-8e85-4c5efe7dcbb7.png">
Please check the configuration of your terminal app.

> 2. Shouldn't dark theme be the default?

Hmm... currently I'm not sure which is better. Waiting for users feedback for a while...

> 3. Port to VSCode

Exactly. We should discuss about this when the light version is out of beta.

**Comment by gkeep** [comment]
>  Please check the configuration of your terminal app.

Yup, that's something on Windows Terminal's end (looks fine in Debian WSL).
> Hmm... currently I'm not sure which is better. Waiting for users feedback for a while...

If you care about my opinion, I think dark should be the default :)

**Comment by cocopon** [comment]
> If you care about my opinion, I think dark should be the default :)

If we care about the compatibility, we should set `set bg=dark` as you said. But ideally users should choose their preferred background explicitly I think... 🤔

**Comment by metalelf0** [comment]
Man, I love it <3 It looks great!

**Comment by connorlay** [comment]
I love this new light theme! For visibility, I added a section to the Alacritty wiki for this new variation: https://github.com/alacritty/alacritty/wiki/Color-schemes#iceberg

**Comment by babygau** [comment]
love it ❤

**Comment by lamartire** [comment]
Perfect light theme. Looking forward for version for iterm2 :)

**Comment by cocopon** [comment]
I think it's enough to remove the public beta flag. Thank you for your help!
