### ISSUE TITLE
Inconsistent terminal.sexy colours

### ISSUE THREAD

**Issue by chinmaya1011** [cocopon/iceberg.vim#71]
Environment:
- Gnome
- Vim 8.2
- Gnome Terminal

The terminal.sexy linked on the readme has background colour #1d1f21 and foreground #c5c8c6 which is inconsistent with the values in the vim and for example the Hyper terminal theme (#161821 and #c6c8d1) respectively. This is also true for the other colours.

**Comment by cocopon** [comment]
That is just a link to terminal.sexy itself and they are default colors of the website. You should import [.Xresources](https://gist.github.com/cocopon/1d481941907d12db7a0df2f8806cfd41) to apply the palette.

**Comment by chinmaya1011** [comment]
OH. Sorry for the confusion!
