### ISSUE TITLE
How to create new colorscheme?

### ISSUE THREAD

**Issue by babygau** [cocopon/iceberg.vim#74]
According to instructions, I could modify _iceberg.vim_ to my liking. what if I wanna give this modified one a new name so that it won't conflict with future plugin update?

**Comment by gkeep** [comment]
As far as I know, you modify `src/iceberg.vim` file to change *color linking* (making certain parts of text specific colors). Change the file's name and change lines 875 and 880 to something else to not cause conficts.

If you want to change *colors* you need to modify files in the `iceberg/palette/` folder and the `colors/iceberg.vim` file.

Before you do, though, if it's not something major (like changing *a lot* of colors) you should just [override colors](https://stackoverflow.com/questions/2440149/override-colorscheme) in your `.vimrc`/`init.vim`.

**Comment by babygau** [comment]
tks u @gkeep
