### ISSUE TITLE
Add support for neovim's built-in LSP&Diagnostics

### ISSUE THREAD

**Issue by woodyZootopia** [cocopon/iceberg.vim#75]
[Neovim 0.5 comes with default LSP feature](https://neovim.io/roadmap/). I started using it, but since iceberg.vim doesn't support it, it's hard to read error/warning text, which is placed along code.

**Comment by woodyZootopia** [comment]
I experimentally created a PR (#76). 
@cocopon if you don't like the coloring/implementation of that PR, let's modify it together or please ignore that and add your own implementation.

**Comment by vladimir-didenko** [comment]
Hi @woodyZootopia. I tried your pull request and found several issues
1. There are no colors defined for underline diagnostics i.e.
```
LspDiagnosticsUnderlineWarning
LspDiagnosticsUnderlineError
LspDiagnosticsUnderlineInformation
LspDiagnosticsUnderlineHint
```
You could look to the nord theme as an example - https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim#L581
2. Error hover background color is not consistent e.g.
![Screenshot from 2021-08-05 10-09-53](https://user-images.githubusercontent.com/1499142/128307231-741b6d6b-bdc0-47b1-abb3-10e28214405f.png)
At the same time warning hover has a consistent background.

**Comment by woodyZootopia** [comment]
@vladimir-didenko Thank you for reporting. It's fixed.

**Comment by babygau** [comment]
@woodyZootopia got any plan to port this to Lua?

**Comment by woodyZootopia** [comment]
It seems like LSP highlighting can be done without my patch since [neovim#15585](https://github.com/neovim/neovim/pull/15585).
I'm leaving this issue open for a while for those who in need, but am going to close it when this patch has been released as stable update.

**Comment by vladimir-didenko** [comment]
> It seems like LSP highlighting can be done without my patch since [neovim#15585](https://github.com/neovim/neovim/pull/15585). I'm leaving this issue open for a while for those in need, but am going to close when it is released as stable.

My understanding is that fix is still required but highlight group names will be different e.g.
```
LspDiagnosticsDefaultWarning -> DiagnosticWarn
LspDiagnosticsDefaultError -> DiagnosticError
```

**Comment by woodyZootopia** [comment]
@vladimir-didenko Oh, that seems correct. Thank you very much, I didn't know that.
So it seems like this patch is still needed but I need to update the PR again to match the highlight group change.

**Comment by woodyZootopia** [comment]
@vladimir-didenko Added the link from Diagnostics to the PR. Please check it out.

**Comment by vladimir-didenko** [comment]
> @vladimir-didenko Added the link from Diagnostics* and pushed it to the PR. Please check it out.

In general looks good but there is the same typo was made for two groups
1. In DiagnosticUnderline* group
```
DiagnosticUnderlineInformation -> DiagnosticUnderlineInfo
DiagnosticUnderlineWarning -> DiagnosticUnderlineWarn
```
2. In DiagnosticSign group 
```
DiagnosticSignWarning -> DiagnosticSignWarn
DiagnosticSignInformation -> DiagnosticSignInfo
```
Thank you!

**Comment by woodyZootopia** [comment]
Oh, sorry. How caress I am...
(by the way, warning/info color has also been changed w.r.t. [@mikepqr 's comment](https://github.com/cocopon/iceberg.vim/pull/76#issuecomment-958664778) in the most recent commit. Please note that and please give a comment if you have any other opinion on the issue)

**Comment by vladimir-didenko** [comment]
> Oh, sorry. How caress I am... (by the way, warning/info color has also been changed w.r.t. [@mikepqr 's comment](https://github.com/cocopon/iceberg.vim/pull/76#issuecomment-958664778) in the most recent commit. Please note that and please give a comment if you have any other opinion on the issue)

Looks almost perfect for me! Thank you! The only issue I found is that Hint hover is hardly readable
![Screenshot from 2021-11-03 16-39-57](https://user-images.githubusercontent.com/1499142/140070876-b63842cb-8999-4526-a0c9-33e9e9b6cfc6.png)

**Comment by woodyZootopia** [comment]
@vladimir-didenko , CC: @mikepqr
Thank you for the quick feedback. I made 'Hint' hover color normal for readability.
Example:
![image](https://user-images.githubusercontent.com/30687489/140077101-7cb2ab1d-2a81-43fb-bfa4-9d9022f0a93a.png)
![image](https://user-images.githubusercontent.com/30687489/140077041-df785e36-1e2f-4f4d-a3c2-c7e5460b854a.png)

**Comment by mikepqr** [comment]
LGTM!

![Screen Shot 2021-11-03 at 9 12 06 AM](https://user-images.githubusercontent.com/370930/140099037-a743b42f-10a1-47b2-bd71-7c8525862577.png)

**Comment by cocopon** [comment]
Sorry for the too late reply... now I'm looking into the issue.

Is there any official documentation about these highlighting groups? I'd like to see them before merging the PR but cannot find them.

**Comment by cocopon** [comment]
Okay, I found the documentation: https://neovim.io/doc/user/diagnostic.html#diagnostic-highlights

**Comment by fragov** [comment]
> Okay, I found the documentation: https://neovim.io/doc/user/diagnostic.html#diagnostic-highlights

@cocopon, you also may check this plugin: https://github.com/tjdevries/colorbuddy.nvim

**Comment by cocopon** [comment]
> you also may check this plugin: https://github.com/tjdevries/colorbuddy.nvim

I'd like to refer the official document because it has the newest and the most accurate information.

Anyway, it's interesting. It seems that plugin is only for Neovim and doesn't provide a compiled file (it may take a time to start up). I'm using my plugin [Pgmnt](https://github.com/cocopon/pgmnt.vim) to build my color schemes.
