### ISSUE TITLE
support for windows terminal

### ISSUE THREAD

**Issue by JDRanpariya** [cocopon/iceberg.vim#79]
Environment:
- windows 
- neovim
- windows terminal

If you have a trouble with coloration and are using Vim/Neovim with terminal:
- [x] Does your Vim support full colors? (`:set termguicolors`)
- [x] Does your terminal support full colors? (e.g. Terminal.app doesn't support it)

format required:
ex: Night Owl

{
            "background": "#011627",
            "black": "#011627",
            "blue": "#82AAFF",
            "brightBlack": "#969696",
            "brightBlue": "#82AAFF",
            "brightCyan": "#7FDBCA",
            "brightGreen": "#22DA6E",
            "brightPurple": "#C792EA",
            "brightRed": "#EF5350",
            "brightWhite": "#FFFFFF",
            "brightYellow": "#FFEB95",
            "cyan": "#21C7A8",
            "foreground": "#D6DEEB",
            "green": "#22DA6E",
            "name": "Night Owl",
            "purple": "#C792EA",
            "red": "#EF5350",
            "white": "#FFFFFF",
            "yellow": "#ADDB67"
        },

**Comment by cocopon** [comment]
Could you explain that JSON? I'm not a Windows user.

**Comment by gkeep** [comment]
Microsoft have released their [Terminal](https://github.com/microsoft/terminal) for Windows not so long ago. 

I'm guessing the issue creator requests the port of the colorscheme to the Windows Terminal? Well, he's in luck!

Basically, this JSON is how custom colorschemes are defined in `settings.json` of the Windows Terminal.

Here's the JSON for Iceberg (will move that to a gist shortly):
```json
            "name" : "Iceberg",

            "cursorColor": "#c6c8d1",
            "selectionBackground": "#1e2132",

            "background" : "#161821",
            "foreground" : "#c6c8d1",

            "black" : "#1e2132",
            "blue" : "#84a0c6",
            "cyan" : "#89b8c2",
            "green" : "#b4be82",
            "purple" : "#a093c7",
            "red" : "#e27878",
            "white" : "#c6c8d1",
            "yellow" : "#e2a478",
            "brightBlack" : "#767676",
            "brightBlue" : "#91acd1",
            "brightCyan" : "#95c4ce",
            "brightGreen" : "#c0ca8e",
            "brightPurple" : "#ada0d3",
            "brightRed" : "#e98989",
            "brightWhite" : "#d2d4de",
            "brightYellow" : "#e9b189"
```

I have made this long ago, but couldn't be bothered to post it somewhere.

**Comment by JDRanpariya** [comment]
Thanks @gkeep 
I was just looking for that 
I think it will be cool if you pull request to add this json

**Comment by cocopon** [comment]
OSS maintainers receive many issues every day. You can help us with more kind, detailed reports. @JDRanpariya
