### ISSUE TITLE
Add support for nvim-treesitter

### ISSUE THREAD

**Issue by ress997** [cocopon/iceberg.vim#82]
I would like to see support for highlighting in the [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter).

- [nvim-treesitter-highlights](https://github.com/nvim-treesitter/nvim-treesitter/blob/b938e4f0fe047a3debcb3708d724905e96f1a58f/doc/nvim-treesitter.txt#L398)

**Comment by brymer-meneses** [comment]
Any updates on this one?

**Comment by woodyZootopia** [comment]
Hi @brymer-meneses @ress997,

Are you still interested in treesitter support?

Adding support for a new plugin to the iceberg.vim is not very difficult. Add new highlights to the `src/iceberg.vim`, install [pgmnt.vim](https://github.com/cocopon/pgmnt.vim), and compile as [written in the README](https://github.com/cocopon/iceberg.vim#building-your-own-iceberg). An updated colorscheme will be written to `colors/iceberg.vim`.

I'm not using treesitter so I can't add the support by myself, but you may find it helpful [my PR](https://github.com/cocopon/iceberg.vim/pull/76/files), which basically does the same thing for Neovim's default LSP. I've just added links from LSP-specific highlights to the existing highlights, and it's working well enough. I suppose you can do in the same way.

Good luck!

**Comment by fragov** [comment]
Any chance @cocopon will have time for this?

**Comment by cocopon** [comment]
Thank you for your patience. To be honest I'm not a tree-sitter user, but now it seems popular enough to add a support. I'll take a look into it.

**Comment by cocopon** [comment]
Added in #96.
