### ISSUE TITLE
color display issue after commit 48a2b28

### ISSUE THREAD

**Issue by zhx-zhang** [cocopon/iceberg.vim#83]
Environment:
- WSL 
- Vim (`:v8.0`)
- Windows Terminal

If you have a trouble with coloration and are using Vim/Neovim with terminal:
**(I'm not sure about either of these)**
- [x] Does your Vim support full colors? (`:set termguicolors`)
- [x] Does your terminal support full colors? (e.g. Terminal.app doesn't support it)

So I haven't updated my iceberg theme for a long time, but after I finally did it, the coloration became something completely different. I did some test, and it seems like the issue happens at commit 48a2b28.

This is the display at commit 63bf6ae (one commit before):
![image](https://user-images.githubusercontent.com/60555905/103056782-e32b1200-456b-11eb-8f19-97771c8d3405.png)

This is the display at commit 48a2b28:
![image](https://user-images.githubusercontent.com/60555905/103056744-cabaf780-456b-11eb-95a8-c522f332dcac.png)

**Comment by cocopon** [comment]
Please make sure your background option by `:set bg`. If it shows `background=light`, you should add `set bg=dark` in your vimrc explicitly. I have added a light version so now you can choose a preferred one.

**Comment by zhx-zhang** [comment]
That's exactly the issue. Thank you so much!
