### ISSUE TITLE
highlight Comment cterm=italic gui=italic doesnt work with this colorscheme

### ISSUE THREAD

**Issue by undefinedDarkness** [cocopon/iceberg.vim#85]
Environment:
- OS - Ubuntu 20.04
- Vim (`:version`) - VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
- Terminal - kitty 0.15.0

If you have a trouble with coloration and are using Vim/Neovim with terminal:
- [ x] Does your Vim support full colors? (`:set termguicolors`)
- [ x] Does your terminal support full colors? (e.g. Terminal.app doesn't support it)

Hello :wave: and Happy New Years :tada: 
Thank you for making this very nice colorscheme.
I have this odd issue where `hi Comment gui=italic cterm=italic term=italic` doesnt work the iceberg.vim colorscheme.
It works with some other color schemes I have installed (nord for one).
My vimrc might have something to do with it, [I uploaded it here](http://0x0.st/-sQR.txt)
This might not be worth opening an issue over heh

**Comment by cocopon** [comment]
Thank you for using Iceberg.

1. Please try it in a minimum configuration. If you remove dependencies of all other plugins, does the problem still occur?
2. Please share a minimum vimrc file.
3. What is a result of `:hi Comment` in your environment?
4. If you run `:hi Comment gui=italic cterm=italic term=italic` manually after startup, does it work correctly?

**Comment by undefinedDarkness** [comment]
I removed all of my configuration only loading the colorscheme and setting it and the italic
```
call plug#begin('~/.vim/plugged')
        Plug 'cocopon/iceberg.vim'
call plug#end()

colorscheme iceberg
hi Comment gui=italic cterm=italic term=italic
```
Still doesnt work
`hi Comment` gives `Comment        xxx term=bold ctermfg=242 guifg=#6b7089 ` which is a bit odd since I did set it after the colorscheme.
Running `:hi Comment gui=italic cterm=italic term=italic` or sourcing the vimrc works fine but it doesnt work when vim loads it automatically

**Comment by cocopon** [comment]
I tried to reproduce the issue with your configuration but I can't. It seems to be caused by your environment. Do other color schemes work fine in your minimum environment?

```vim
" 85.vimrc
set rtp+=~/.vim/vim-plug

call plug#begin('~/.vim/plugins')
  Plug 'cocopon/iceberg.vim'
call plug#end()

colorscheme iceberg
hi Comment gui=italic cterm=italic term=italic
```

```
$ vim -u 85.vimrc
```

```
:hi Comment

Comment        xxx term=italic cterm=italic ctermfg=242 gui=italic
                   guifg=#6b7089
```

**Comment by undefinedDarkness** [comment]
Since it seems to be an issue with my enviroment, I edited `colors/iceberg.vim` (I had followed the advice on the previous issue of this and only edited light mode, silly me) and changed the highlight lines to add the italics and that seems to have done the trick, not a great solution but a solution none the less.
