### ISSUE TITLE
When trying to install, the plugin asks to remove itself and then crashes

### ISSUE THREAD

**Issue by wantyapps** [cocopon/iceberg.vim#89]
Environment:
- OS macOS Big Sur
- Vim (`:version`) NVIM v0.5.0-dev+nightly-30-gdc3ca16a9
- Terminal Kitty

If you have a trouble with coloration and are using Vim/Neovim with terminal:
- [x] Does your Vim support full colors? (`:set termguicolors`)
- [x] Does your terminal support full colors? (e.g. Terminal.app doesn't support it)

I tried installing plugins, and it asks this: Removing /Users/uriarev/.local/share/nvim/site/pack/packer/opt/packer.nvim. OK?
<img width="1440" alt="Screen Shot 2021-02-25 at 7 57 42" src="https://user-images.githubusercontent.com/56798701/109110103-273ebc80-773f-11eb-8ca9-45e49e3160d8.png">

And when I press yes, it installs and it is all ok. But when I later launch nvim:

<img width="1440" alt="Screen Shot 2021-02-25 at 7 59 32" src="https://user-images.githubusercontent.com/56798701/109110242-68cf6780-773f-11eb-8121-7db1c1760c23.png">

**Comment by wantyapps** [comment]
Please answer ASAP.

**Comment by wantyapps** [comment]
BTW: I found a workaround which is just ignoring the question, but I want to remove it completely...

**Comment by wantyapps** [comment]
SORRY! WRONG REPO!

**Comment by cocopon** [comment]
Okay, but

> Please answer ASAP.

I think you should not say things like that. OSS maintainers are NOT your customer support.
