### ISSUE TITLE
Even with Termux!

### ISSUE THREAD

**Issue by laddge** [cocopon/iceberg.vim#91]
Thank you for creating such a wonderful theme.
I love this theme in vim.
And influenced by [this issue](https://github.com/cocopon/iceberg.vim/issues/3), I created a color scheme file for Termux.
It is in this repository -> [laddge/termux-iceberg](https://github.com/laddge/termux-iceberg).
If you like, please write it in the README.

**Comment by gkeep** [comment]
Looks good, thank you!

**Comment by mamg22** [comment]
Awesome! thanks for sharing.

btw, I added iceberg as a colorscheme option in the [termux-styling](https://github.com/termux/termux-styling) plugin a [few months ago](https://github.com/termux/termux-styling/commit/6fcf4e3d795e74e38527e70ec482f6d828e319db) based on that same Xresources file. So it is also easily available for people with that plugin installed.

**Comment by laddge** [comment]
Oh, I didn't know.
Thank you😚😚😚
