### ISSUE TITLE
iceberg.vim isn't adapting well on some terminals

### ISSUE THREAD

**Issue by WMCB-Tech** [cocopon/iceberg.vim#92]
Environment:
- OS: Windows 10 
- Vim (8.2.2815)
- Terminal: Windows Terminal Preview

If you have a trouble with coloration and are using Vim/Neovim with terminal:
- [x] Does your Vim support full colors? (`:set termguicolors`)
- [x] Does your terminal support full colors? (e.g. Terminal.app doesn't support it)

---

some Terminals like windows terminal and (cmd.exe) also have issues with `iceberg.vim`, the entire vim screen is white when using `iceberg.vim` colorscheme, while other terminal emulators (kitty, xfce4-terminal) adapts it just fine

here's the video shown:
https://user-images.githubusercontent.com/65075766/129345428-f11bf495-535c-4d5c-ab71-5ad23bb7c15d.mp4

while manually re-setting `iceberg.vim` colorscheme works via `:colorscheme iceberg` but it's not a ideal solution

**Comment by gkeep** [comment]
Please provide your `.vimrc`/`init.vim`.

**Comment by WMCB-Tech** [comment]
@gkeep here's my `.vimrc`
```
syntax on
colorscheme iceberg

" text editor config
set wrap!
set tabstop=8
set shiftwidth=8
set expandtab

" use i-beam cursor block when in INSERT mode
" https://github.com/thestinger/termite/issues/691
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
```

**Comment by gkeep** [comment]
Can you try adding `set background=dark` to your `.vimrc` and see if that fixes the issue?

Possibly related: https://github.com/cocopon/iceberg.vim/issues/62#issuecomment-629300599

**Comment by WMCB-Tech** [comment]
It works! thank you for the solution. i appreciate it! 👍
