### ISSUE TITLE
Changing Rust docs colors

### ISSUE THREAD

**Issue by Jarema** [cocopon/iceberg.vim#95]
Hi,

Simple question, I hope: which values/lines of codes should be changed so docs comment (`//!` and `///`) would have the same colors as normal comments (`//`) in Rust?

Thanks in advance for help. I really love that theme, though the docs colours really stand out.

I do not request change in the repo (unless it would fit more folks). It's just a request to point me into right direction.

**Comment by gkeep** [comment]
You can override these colors by adding `highlight SpecialComment guifg=#6b7089` for dark theme and `highlight SpecialComment guifg=#8389a3` for light theme to your config file. 

If you often switch between light and dark variants you can wrap the override in an `if` statement like this:
```vim
if &background == 'light'
    highlight SpecialComment guifg=#8389a3
else
    highlight SpecialComment guifg=#6b7089
endif
```

![image](https://user-images.githubusercontent.com/20600053/146727802-f5b9a743-104b-46b7-a7c0-c49dc0f3558b.png)

**Comment by Jarema** [comment]
Thanks for quick response and help!
